# Site settings
title: "Mike JS. Choi"
email: mkchoi212@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  0xBEEFCAFE
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: bananamlkshake2
github_username: mkchoi212 

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rouge 

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed

gems:
  - jekyll-paginate


