# Site settings
title: "0xDEADBEEF"
description: > 
    Hi, I'm Mike. Here, I write about random computer musings. 

author: Mike JS. Choi
email: mkchoi212@icloud.com
baseurl: ""
url: "https://www.deadbeef.me" # the base hostname & protocol for your site
twitter_username: bananamlkshake2
github_username:  mkchoi212
disqus_id: deadbeef-me
google_analytics_id: UA-101802837-1

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed

exclude: [vendor]
